server:
  root_url: https://grafana.parkloyalty.com
grafana.ini:
  smtp:
    enabled: true
    host: smtp.gmail.com:587
    from_address: admin@grafana.localhost
    from_name: ParkLoyalty-Grafana
    skip_verify: true
smtp:
  existingSecret: grafana-smtp
persistence:
  enabled: true
  size: 5Gi